# Generated by Django 4.0.7 on 2022-10-02 23:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to=core.models.post_image_file_path),
        ),
    ]
