# Generated by Django 4.0.7 on 2022-10-03 19:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AumFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_for', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.aum_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='AumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_for', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.aum_file_path)),
            ],
        ),
    ]
