# Generated by Django 4.0.7 on 2022-10-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aumfile_aumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aumfile',
            name='desc',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='aumfile',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aumimage',
            name='desc',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='aumimage',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
