# Generated by Django 4.0.8 on 2022-10-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='on_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.post'),
        ),
    ]
